[package]
name = "death-calendar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https: //doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = { version = "3.2.15", features = ["unstable-doc"] }
date_time_parser = "0.1.1"
gregorian = "0.2.3"
svg = "0.10.0"
