[package]
name = "death-calendar"
version = "0.2.1"
edition = "2021"
description = "Calculate how much time you have until your ultimate demise."
license = "AGPL-3.0-or-later"
repository = "https://github.com/wildwestrom/death-calendar"
readme = "README.org"
keywords = ["life", "death", "time", "calendar"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https: //doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "3.2" , features = ["derive"] }
date_time_parser = "0.1"
gregorian = "0.2"
svg = "0.10"
hex_color = "1"
