[package]
name = "death-calendar"
version = "0.3.1"
edition = "2021"
description = "Calculate how much time you have until your ultimate demise."
license = "GPL-3.0-or-later"
repository = "https://github.com/wildwestrom/death-calendar"
readme = "README.md"
keywords = ["life", "death", "time", "calendar"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https: //doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
gregorian = { git = "https://github.com/mattfbacon/gregorian-rs", features = [
  "serde",
] }
svg = "0.10"
hex_color = "2"
anyhow = "1"
figment = "0.10.8"
figment_file_provider_adapter = "0.1.0"
serde = { version = "1", features = ["derive"] }
csscolorparser = "0.6"
