[package]
name = "death-calendar"
version = "0.3.0"
edition = "2021"
description = "Calculate how much time you have until your ultimate demise."
license = "GPL-3.0-or-later"
repository = "https://github.com/wildwestrom/death-calendar"
readme = "README.md"
keywords = ["life", "death", "time", "calendar"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https: //doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
gregorian = "0.2"
svg = "0.10"
hex_color = "2"
