[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.lint]
script = '''
cargo clippy -- \
  -D clippy::all \
  -D clippy::pedantic \
  -D clippy::nursery \
  -D clippy::restriction \
  -D clippy::cargo \
  -A clippy::integer_arithmetic \
  -A clippy::arithmetic \
  -A clippy::integer_division \
  -A clippy::missing-docs-in-private-items \
  -A clippy::implicit_return \
  -A clippy::separated_literal_suffix \
  -A clippy::std_instead_of_core
'''

[tasks.cargo-fmt-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.toml-fmt-check]
command = "taplo"
args = ["fmt", "--check", "Cargo.toml", "Makefile.toml"]

[tasks.fmt]
dependencies = ["cargo-fmt-check", "toml-fmt-check"]

[tasks.release]
dependencies = ["clean"]
command = "cargo"
args = ["build", "--release"]

[tasks.ci]
dependencies = ["fmt", "lint", "test", "release"]
