# Clean
[tasks.clean]
command = "cargo"
args = ["clean"]

# Test
[tasks.test]
command = "cargo"
args = ["test"]

# Lint
[tasks.lint]
script = '''
cargo clippy -- \
  -D clippy::all \
  -D clippy::pedantic \
  -D clippy::nursery \
  -D clippy::restriction \
  -D clippy::cargo \
  -A clippy::integer_arithmetic \
  -A clippy::arithmetic \
  -A clippy::integer_division \
  -A clippy::missing-docs-in-private-items \
  -A clippy::implicit_return \
  -A clippy::separated_literal_suffix \
  -A clippy::std_instead_of_core
'''

# Format

## Check
[tasks.rust-fmt-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.toml-fmt-check]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--help" }
command = "taplo"
args = ["fmt", "--check", "*.toml"]

[tasks.fmt-check]
dependencies = ["rust-fmt-check", "toml-fmt-check"]

## Fix
[tasks.rust-fmt-fix]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.toml-fmt-fix]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--help" }
command = "taplo"
args = ["fmt", "*.toml"]

[tasks.fmt-fix]
dependencies = ["rust-fmt-fix", "toml-fmt-fix"]

# Build
[tasks.release]
dependencies = ["clean"]
command = "cargo"
args = ["build", "--release"]

# Final
[tasks.build]
dependencies = ["fmt-fix", "lint", "test"]

[tasks.ci]
dependencies = ["fmt-check", "lint", "test", "release"]
