[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.lint]
script = { file = "bin/clippy.sh" }
dependencies = ["format"]

[tasks.release]
dependencies = ["clean"]
command = "cargo"
args = ["build", "--release"]

[tasks.ci]
dependencies = [
    "lint",
    "test",
    "release",
]
