* Death Calendar

  Ever wonder how many days you have left to live?\\
  Death Calendar can show you at a glance.

** Installation
Make sure you have a working rust toolchain.

#+begin_src shell
  git clone https://github.com/wildwestrom/death-calendar
  cd death-calendar
  cargo install
#+end_src

** License
   Death Calendar: Calculate how much time you have until your ultimate demise.\\
   Copyright © 2021 Christian Westrom

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
